### Create a new workspace (admin)
POST {{host}}/workspaces
Accept: application/json
Content-Type: application/json

{
  "owner": "pawelkielb-admin",
  "hooks": {
    "onUpdate": {
      "file": "task.yaml",
      "url": "http://localhost:8080/hooks/onUpdate"
    }
  }
}

### Create a new worksapce (user)
POST {{host}}/workspaces
Accept: application/json
Content-Type: application/json

{
  "owner": "pawelkielb-user",
  "template": "18efd86b-e410-42bd-913c-87e0dfaed2d4",
  "readOnlyFiles": [
    "README.md",
    "src/file.txt"
  ]
}

### Add files
POST {{host}}/workspaces/18efd86b-e410-42bd-913c-87e0dfaed2d4/files
Accept: application/json
Content-Type: application/json

[
  {
    "path": "src/file1.txt",
    "content": "Zadanie 1"
  },
  {
    "path": "task.yaml",
    "content": "{ ... }"
  }
]
