### Create a new workspace (admin)
POST {{host}}/workspace
Accept: application/json
Content-Type: application/json

{
  "owner": "pawelkielb-admin",
  "hooks": {
    "onUpdate": {
      "file": "task.yaml",
      "url": "http://localhost:8080/hooks/onUpdate"
    }
  }
}

### Create a new worksapce (user)
POST {{host}}/workspace
Accept: application/json
Content-Type: application/json

{
  "owner": "pawelkielb-user",
  "template": "sdjafjlx138",
  "readOnlyFiles": [
    "README.md",
    "src/file.txt"
  ]
}

### Add files
POST {{host}}/workspace/4586cc65-c98a-4014-aeb2-09ce67102a2f/files
Accept: application/json
Content-Type: application/json

[
  {
    "path": "src/file1.txt",
    "content": "Zadanie 1"
  },
  {
    "path": "task.yaml",
    "content": "{ ... }"
  }
]
